-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."softcartDimDate"
(
    dateid integer NOT NULL,
    day_of_month integer,
    week_of_year integer,
    month_of_year integer,
    year integer,
    full_date date,
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCategory"
(
    category_id integer NOT NULL,
    orderid integer,
    category character varying(40),
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimItem"
(
    item_id integer NOT NULL,
    category_id integer,
    item character varying(80),
    PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCountry"
(
    item_id integer,
    "Country" character varying(80)
);

CREATE TABLE IF NOT EXISTS public."softcartFactSales"
(
    orderid integer,
    item_id integer,
    category_id integer,
    price numeric(32),
    dateid integer,
    PRIMARY KEY (orderid)
);

ALTER TABLE IF EXISTS public."softcartDimDate"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."softcartFactSales" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartDimCategory"
    ADD FOREIGN KEY (orderid)
    REFERENCES public."softcartFactSales" (orderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartDimItem"
    ADD FOREIGN KEY (item_id)
    REFERENCES public."softcartFactSales" (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (item_id)
    REFERENCES public."softcartDimCountry" (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;